# Generated by Django 5.1.15 on 2026-09-17 10:20

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("billing_month", models.DateField()),
                ("monthly_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("scheduled_days", models.IntegerField(default=0)),
                ("served_days", models.IntegerField(default=0)),
                ("paused_days", models.IntegerField(default=0)),
                ("skipped_days", models.IntegerField(default=0)),
                (
                    "daily_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("GENERATED", "Generated"),
                            ("UNPAID", "Unpaid"),
                            ("PARTIALLY_PAID", "Partially Paid"),
                            ("PAID", "Paid"),
                        ],
                        default="GENERATED",
                        max_length=20,
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bills",
                        to="customers.customer",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bills",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-billing_month"],
                "unique_together": {("customer", "subscription", "billing_month")},
            },
        ),
    ]
