# Generated by Django 5.1.15 on 2026-09-17 11:13

import django.db.models.deletion
from django.db import migrations, models


def seed_subscription_customers(apps, schema_editor):
    Subscription = apps.get_model("subscriptions", "Subscription")
    SubscriptionCustomer = apps.get_model("subscriptions", "SubscriptionCustomer")
    for subscription in Subscription.objects.all():
        SubscriptionCustomer.objects.get_or_create(
            subscription_id=subscription.id,
            customer_id=subscription.customer_id,
            start_date=subscription.start_date,
            defaults={"end_date": subscription.end_date},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transfer_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_subscription_transfers",
                        to="customers.customer",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers",
                        to="subscriptions.subscription",
                    ),
                ),
                (
                    "to_customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_subscription_transfers",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["transfer_date", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_periods",
                        to="customers.customer",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_periods",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "ordering": ["start_date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("subscription", "customer", "start_date"),
                        name="unique_subscription_customer_period_start",
                    )
                ],
            },
        ),
        migrations.RunPython(seed_subscription_customers, migrations.RunPython.noop),
    ]
