# Generated by Django 5.1.15 on 2026-09-17 11:13

import django.db.models.deletion
from django.db import migrations, models


def seed_delivery_customers(apps, schema_editor):
    Delivery = apps.get_model("deliveries", "Delivery")
    for delivery in Delivery.objects.select_related("subscription"):
        delivery.customer_id = delivery.subscription.customer_id
        delivery.save(update_fields=["customer"])


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
        ("deliveries", "0001_initial"),
        ("subscriptions", "0002_subscriptiontransfer_subscriptioncustomer"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deliveries",
                to="customers.customer",
            ),
        ),
        migrations.RunPython(seed_delivery_customers, migrations.RunPython.noop),
    ]
